### ISSUE TITLE
EPUB Accessibility FAQ

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#1817]
The FAQ is referenced in a note at the end of section 1.1, but is still an IDPF document: https://idpf.github.io/epub-guides/a11y-faq/

It's also needs revision, at least with respect to the answer about using URLs for the conformance identifier.

Looks like we may need to port this over to a note.

**Comment by iherman** [comment]
I am not sure it is worth the trouble of a note. What about a properly edited github page? We can even set it up in its own repository if needed.

Just an idea...

**Comment by mattgarrish** [comment]
> What about a properly edited github page?

Works for me!

> We can even set it up in its own repository if needed.

Maybe it could go in publ-a11y, or does it need to be a WG repository?

**Comment by iherman** [comment]
> Maybe it could go in publ-a11y, or does it need to be a WG repository?

either way works for me, but I am not in that task force...

**Comment by mattgarrish** [comment]
publ-a11y is intended for use by all publishing@w3c groups, so it seems like as good a place as any. But are there any issues with referencing a document with no real provenance? I know it's only referenced from a note, but how do we identify document ownership outside of respec? It's not a CG document, so we can't make it a CG report.

@avneeshsingh any thoughts on this?

**Comment by avneeshsingh** [comment]
It is FAQ, a kind of live document, that explains reasoning behind decisions made for "EPUB Accessibility".
If we want to make it a CG report, then we need to go through a light weight process of accessibility task force in Publishing CG. And it has a closer association with EPUB Accessibility which is not in Publishing CG.
Since it is a more of a live document, it would be fine to have it as a document with no explicit status like WG Note or CG report.
pub-a11y is fine for it.

**Comment by mattgarrish** [comment]
> And it has a closer association with EPUB Accessibility which is not in Publishing CG.

What if we just put it in the wiki for this repository? That might be simplest of all.

**Comment by avneeshsingh** [comment]
Wiki may look casual visually. But as per W3C's spectrum of documents, both has the same status, it may be a webpage on github or Wiki  on GitHub, .

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-09-23-epub-a11y#section1) on 2021-09-23

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-09-23-epub-a11y#resolution1):  Move EPUB Accessibility FAQ to wiki on epub specs repo***

<details><summary><i>View the transcript</i></summary>

### 1. EPUB Accessibility FAQ 

_See github issue [#1817](https://github.com/w3c/epub-specs/issues/1817)._




**Avneesh Singh:** let's talk about the first agenda item  
… Matt raised this issue yesterday  

_See github issue [#1819](https://github.com/w3c/epub-specs/issues/1819)._




**Matt Garrish:** Something I bumped into while reviewing the document  
… we still have a reference to the old IDPF github repo  
… it's basically that we need to move this document if we want to still reference  
… I think it's ok, I've discussed this with Ivan  
… there's a way to keep this in Respec without formally publishing  
… bigger problem is #1819, what do we do about the optimization registry  
… the first one is easier, we publish it and update the reference  
… the registry issue is more complicated  
… it's basically a list of optimization standards  
… what do we do with it?  
… it's kind of process heavy, if there's a way to add a registry as a W3C registry  
… do we move it  
… I don't know what is the best approach  

**Avneesh Singh:** My understanding is that we don't want to give W3C status to any of these  
… I would say an HTML page sitting in the repo would be find for now  

**Matt Garrish:** Should we still call it a registry?  

**Avneesh Singh:** Yes the name can cause confusion  
… we shouldn't call it a registry  

**Matt Garrish:** Ok we'll move them away, and change the name  

**John Foliot:** I just wanted to point out, there is a way to host notes  
… the WAI domain has many  
… they're hosted in the TR space, but as non-normative notes  
… We have many for user requirements and things like that  
… making content accessible is one of them  
… tagged as working group notes  

> *John Foliot:* [https://www.w3.org/TR/coga-usable/](https://www.w3.org/TR/coga-usable/)

**Matt Garrish:** That was my original proposal  
… Ivan had suggested that we might not need a full note  
… I don't have a strong opinion  
… we can do them as notes  
… do they need formal standing  

> *Bill Kasdorf:* how useful is the information in them?

**Matt Garrish:** it's a general FAQ and some documents  
… once we get into note territory our hands are a little more bound  
… we'd need a WG  
… to vote and approve  

**John Foliot:** Would it not be under the EPUB WG  

**Matt Garrish:** If it's still running  

**Avneesh Singh:** WG Notes have process  

**John Foliot:** That seems like a positive  

**Avneesh Singh:** These particular notes are more challenging ownership wise  

**George Kerscher:** We did these when we were establishing the baseline of EPUB accessibility  
… we didn't have KB back them  
… could we add them into the KB  
… the registry is just a list of optimized standards for various things.  
… It's just informative  
… I don't know if that could also be an item in the KB  

**Avneesh Singh:** I would say for the list of optimized specifications if it's in the KB it's ok  
… the FAQs for the a11y spec is more tied up with EPUB Accessibility  

**Matt Garrish:** Agreed  
… we have documents like this in the repo right now  
… it's more lightweight, but we've published notes for other things  
… it's not quite a specification, it's not quite guidance, it's more background information  

**Avneesh Singh:** If we want to keep it in the epub-specs repo, a wiki might work  

**Gregorio Pellegrino:** We have the KB, is it worth it to do all of this work?  

**Matt Garrish:** This is going back to design decisions  
… why we use schema  
… why things don't overlap with WCAG, it's not something we can farm out, it's very specific to the EPUB accessibility doc  
… it's not obsolete, but it's getting there  
… the spec has been out long enough now  

**Avneesh Singh:** Let's propose to put it on a wiki in the epub-specs space  
… it will not conflict with official notes  

> **Proposed resolution: Move EPUB Accessibility FAQ to wiki on epub specs repo** *(Avneesh Singh)*

> *Wendy Reid:* +1

> *Matt Garrish:* +1

> *Bill Kasdorf:* +1

> *Gregorio Pellegrino:* +1

> *Charles LaPierre:* +1

> *George Kerscher:* +1  

> *Ben Schroeter:* +1

> *John Foliot:* +1

> ***Resolution #1: Move EPUB Accessibility FAQ to wiki on epub specs repo***

</details>
