### ISSUE TITLE
Invalid file name characters

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#1921]
As discussed on the call today (2021-11-19), do we want to consider changing this requirement:

> File Names MUST NOT use the following [Unicode] characters, as commonly used operating systems may not support these characters consistently:

to a "SHOULD NOT"?

We could supplement such a change by adding a note that, when interoperability is key, authors should treat the list as a set of characters to avoid.

**Comment by dauwhe** [comment]
I don't think we should change this. URL parsing does interesting things with the reverse solidus and question mark, which makes it difficult or impossible to use them in links. More of those characters would have to be percent-encoded in links. The zip spec specifically forbids the reverse solidus. 

My sense is that there are lots of disadvantages to using such characters. Are content authors asking for this?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-12-09-epub#section1) on 2021-12-09

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-12-09-epub#resolution1):  Close issue 1921 with no change.***

<details><summary><i>View the transcript</i></summary>

### 1. Invalid file name characters (issue epub-specs#1921)

_See github issue [epub-specs#1921](https://github.com/w3c/epub-specs/issues/1921)._




**Dave Cramer:** there has been some back and forth with the i18n folks about our restrictions on file naming.  
… mgarrish suggested that we change MUST NOT on list of forbidden chars in file names to SHOULD NOT.  

> *Murata Makoto:* +1, but why did Matt propose this?

**Dave Cramer:** i don't agree, a lot of chars are on that list for a good reason, e.g. to allow for moving epubs across OS.  
… file called "?.html" could not be linked to, for example, because of interaction with URL parser.  
… also, not aware of any authors asking to use these characters in epub content.  
… also note that we are not restricting any language in these forbidden chars.  

**Brady Duga:** did i18n specify which countries would be impacted by not allowing these chars?.  

**Dave Cramer:** i think this came from mgarrish wondering whether we should just make the whole list a should rather than selectively taking things out of the forbidden list.  
… e.g. emoji combining chars.  

**Brady Duga:** agree that there is not a reason to add these, plus, these restrictions are applicable to file names - opaque to the reader.  

> **Proposed resolution: Close issue 1921 with no change.** *(Wendy Reid)*

> *Murata Makoto:* +1.

> *Toshiaki Koike:* +1.

> *John Roque:* +1.

> *Shinya Takami (高見真也):* +1.

> *Wendy Reid:* +1.

> *Dave Cramer:* +1.

> *Brady Duga:* +1.

> *Matthew Chan:* +1.

> *John Roque:* +1.

> *Shinya Takami (高見真也):* +1.

> *Murata Makoto:* +1, again.

> *Masakazu Kitahara:* +1.

> ***Resolution #1: Close issue 1921 with no change.***

</details>
