### ISSUE TITLE
Normatizing the fixed layout property statements 

### ISSUE THREAD

**Issue by wareid** [mattgarrish/epub-revision#1936]
The Fixed Layout properties section of the RS spec makes a number of informative default statements for the various `rendition` properties, but only one of them is a normative statement. 

> The default value reflowable MUST be assumed by EPUB Reading Systems as the global value if no meta element carrying this property occurs in the metadata section section [EPUB-33]. 

The default value statements for `rendition:orientation` and `rendition:spread` are both informative (and the same). 

> The default global value is auto if no meta element carrying this property occurs in the metadata section.

I would propose making these both normative MUST statements to match the statement made for `rendition:layout` and to clarify this section.

**Comment by mattgarrish** [comment]
Earlier in the revision we changed from Reading Systems must support the default value to the current prose without a normative keyword because it was said the statements weren't useful for auto values: https://github.com/w3c/epub-specs/issues/1313

The assertion cannot be failed, but that was always by design to allow the default behaviour of reading systems to pass.

Are we okay with testing auto again?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-12-09-epub#section3) on 2021-12-09

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-12-09-epub#resolution2):  Elevate the default behaviour statements for `rendition:orientation` and `rendition:spread` to MUSTs.***

<details><summary><i>View the transcript</i></summary>

### 3. Normatizing the fixed layout property statements  (issue epub-specs#1936)

_See github issue [epub-specs#1936](https://github.com/w3c/epub-specs/issues/1936)._




**Wendy Reid:** i noticed that in RS spec we say in `rendition:layout` that the default value is a MUST.  
… but for the other 2 FXL properties even though we also define default behaviour, we don't make those statements normative.  

**Dave Cramer:** there are a couple instances where we say that the default value MUST be assumed, but i didn't know how that would be testable.  

**Wendy Reid:** the default behaviour is auto, and that means to respect what the RS is doing.  
… so the test would pass if the epub appears in way that would respect the app settings or the user settings.  
… which is essentially what auto is meant to do.  

**Brady Duga:** you could not specify in one case and specify in another case, and if the result is the same then the RS passes?.  

**Wendy Reid:** my proposal was to turn the 2x non-normative default behaviour statements into normative MUSTs.  
… i've already made the tests for both of them.  

**Dave Cramer:** so we just ask mgarrish to made the change, then.  

> **Proposed resolution: Elevate the default behaviour statements for `rendition:orientation` and `rendition:spread` to MUSTs.** *(Wendy Reid)*

> *Brady Duga:* +1.

> *Shinya Takami (高見真也):* +1.

> *Wendy Reid:* +1.

> *John Roque:* +1.

> *Matthew Chan:* +1.

> *Toshiaki Koike:* +1.

> *Theresa O'Connor:* +1.

> *Murata Makoto:* +1.

> *Dave Cramer:* +1.

> *Masakazu Kitahara:* +1.

> ***Resolution #2: Elevate the default behaviour statements for `rendition:orientation` and `rendition:spread` to MUSTs.***

</details>
