### ISSUE TITLE
Reading Systems and Media Overlays...

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#1991]
This may be opening the flood gates, but… at the moment, the RS Specification [says about MO](https://w3c.github.io/epub-specs/epub33/rs/#sec-media-overlays) that 

> Reading Systems MAY support [Media Overlays](https://www.w3.org/TR/epub-33/#sec-media-overlays)

why is this is so weak? Shouldn't we say, at least that they _SHOULD_ support them? Where does this statement come from?

@wareid @dauwhe @mattgarrish @avneeshsingh @marisademeglio

**Comment by mattgarrish** [comment]
This is what I was getting at in #1986 

Support is optional in reading systems and warned it's likely not interoperable in the authoring section. If that's the case, should we be claiming to support it at all?

We can push it up to a recommendation or requirement, but if we do that what are the interoperability problems? Is it only due to a lack of support or what else needs solving?

**Comment by marisademeglio** [comment]
I agree that "MAY support MO" feels weak. 

In our context, what is the difference between [MAY](https://datatracker.ietf.org/doc/html/rfc2119#section-5) and [SHOULD](https://datatracker.ietf.org/doc/html/rfc2119#section-3)?

**Comment by wareid** [comment]
> We can push it up to a recommendation or requirement, but if we do that what are the interoperability problems? Is it only due to a lack of support or what else needs solving?

I don't think we have interoperability issues if we raise it to a SHOULD, considering that still provides reading systems an out. MO is pretty strongly supported, so this change would just help to raise content creator confidence that a book with MO is more likely to be supported than a MAY would suggest.

**Comment by dauwhe** [comment]
I know back in the day EPUB (well, OEB) did not require a lot of things because some implementations might be voice only, some would be purely visual, etc. Maybe the circumstances that led to those kinds of choices have changed in the last (checks watch) twenty years.

**Comment by marisademeglio** [comment]
> I know back in the day EPUB (well, OEB) did not require a lot of things because some implementations might be voice only, some would be purely visual, etc. Maybe the circumstances that led to those kinds of choices have changed in the last (checks watch) twenty years.

Yeah I remember when MO was new, the prevailing opinion was to introduce it gently. Perhaps the MAY was along those lines.

**Comment by mattgarrish** [comment]
> Yeah I remember when MO was new, the prevailing opinion was to introduce it gently.

My suspicion is it was also made optional because not all reading systems support audio playback, plus the functionality wouldn't have been as mainstream when we did EPUB 3. We should probably consider audio support generally as part of any recommendation, though. The usual: "If it has the capability to render pre-recorded audio, it SHOULD ...".

> I don't think we have interoperability issues if we raise it to a SHOULD

I agree for XHTML, but we have a weird two-part optional situation where SVG support isn't required. I can't explain that discrepancy other than no one would have been doing synchronized SVGs at the time (DAISY or mainstream).

That's why that note in the authoring section strikes me as an odd red flag:

> While EPUB Creators may use Media Overlays with [SVG Content Documents](http://localhost:120/core/#dfn-svg-content-document), playback behavior might not be consistent and therefore interoperability is not guaranteed.

Must reading systems also support SVG to be consistent with XHTML? Should they also support?

There's no explanation in either specification for this note, beyond that support for SVG in media overlays is optional. But SVG support generally is required, so what is the holdup between supporting XHTML vs. SVG?

If it no longer applies, can we drop it?

**Comment by avneeshsingh** [comment]
+1 for changing may to should for Media Overlays.

Regarding SVG, may be it requires separate issue for discussion. If Media Overlays is synchronizing audio with SVG as an image then it is straight forward. But if we want Media Overlays to synchronize audio with XML elements inside SVG, then we need to check if reading systems have made sufficient progress for doing it.

**Comment by iherman** [comment]
> 
> Regarding SVG, may be it requires separate issue for discussion. If Media Overlays is synchronizing audio with SVG as an image then it is straight forward. But if we want Media Overlays to synchronize audio with XML elements inside SVG, then we need to check if reading systems have made sufficient progress for doing it.

I have created a simple test for MO+SVG yesterday, see https://github.com/w3c/epub-tests/pull/118. I have run the test on two RS-s so far (Thorium and Colibrio Web app) but it did not work as expected (still to be checked whether this is a bug in the test or not). I think the goal is to sync with XML elements indeed.

The whole MO section is problematic with respect of interoperability at this point: all the 6-7 tests I have put together the last few days have problems. Hence the impossibility to elevate the _MAY_ to _MUST_ (but a _SHOULD_ gives a better signal in my view). (Spine level) SVG is probably a bit in a worse position than XHTML but, at this point, we may want to aim high and keep it on the same level as the rest. @marisademeglio, @dlazin, and I agreed yesterday that more MO+SVG tests would be needed; we can draw conclusion later in the CR phase to see if we need some special consideration for SVG in this respect...

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-02-11-epub#section2) on 2022-02-11

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-02-11-epub#resolution1):  Elevate requirement for media overlays to a SHOULD, close issue 1991.***

<details><summary><i>View the transcript</i></summary>

### 2. Reading Systems and Media Overlays... (issue epub-specs#1991)

_See github issue [epub-specs#1991](https://github.com/w3c/epub-specs/issues/1991)._




**Wendy Reid:** we were doing our RS and MO testing, and realized that current language says that RS may support MO.  
… given how MO are used these days, i think it makes sense to push that up to a should.  
… this still gives room to those RS who can't support audio, but there are definitely more than 2 independent implementations of MO these days.

**Ivan Herman:** i was writing tests for MO and realized this point.  
… is this a leftover from when an earlier version of the spec, or was this deliberate?.  

**Matt Garrish:** i think it came over from DAISY side in 3.0, since we weren't sure at the time what the uptake from mainstream RS would be.  
… don't remember any specific discussion about the level of conformance at the time.  
… it was just a brand new feature, so we didn't want to start by positioning it as critical feature.  
… but that's just my opinion.  

**Dan Lazin:** i would propose as a general guideline that support for features should never be below a SHOULD.  
… MAY should be reserved for behavioural things.  
… if I am RS, and a I see a mishmash of requirement levels, i'm not sure how to interpret that.  

> *Ivan Herman:* +1 to dan.

**Matt Garrish:** if you put it in context of audio support being required for RS, we weren't requiring that either.  
… maybe if you support audio in your RS, then you should also support MO playback.  
… less broad than just saying SHOULD support MO across the board.  

**Dan Lazin:** can whoever is making the PR review other features, and elevate in the same way?.  

> **Proposed resolution: Elevate requirement for media overlays to a SHOULD, close issue 1991.** *(Wendy Reid)*

**Wendy Reid:** i worry that that will turn up something where raising the conformance level will be controversial....  

> *Ivan Herman:* +1.

> *Dan Lazin:* +1.

> *Zheng Xu (徐征):* +1.

> *Matt Garrish:* +1.

> *Laura Brady:* +1.

> *Charles LaPierre:* +1.

> *Avneesh Singh:* +1.

> *Ben Schroeter:* +1.

> *Wendy Reid:* +1.

> *Masakazu Kitahara:* +1.

**Dan Lazin:** then if in the course of reviewing you locate other similar feature support issues, can you open issues for those?.  

**Ivan Herman:** yes, okay.  

> ***Resolution #1: Elevate requirement for media overlays to a SHOULD, close issue 1991.***

</details>

**Comment by mattgarrish** [comment]
(Restating [this comment](https://github.com/w3c/epub-specs/pull/1993#issuecomment-1039099715) here and reopening the issue as it will take another PR to correct.)

Media overlays were already recommended in the core media type section:

> If it has the capability to render pre-recorded audio, it MUST support the [audio Core Media Type Resources](https://www.w3.org/TR/epub-33/#cmt-grp-audio) [[EPUB-33](https://w3c.github.io/epub-specs/epub33/rs/#bib-epub-33)] and SHOULD support Media Overlays [[EPUB-33](https://w3c.github.io/epub-specs/epub33/rs/#bib-epub-33)].

https://w3c.github.io/epub-specs/epub33/rs/#confreq-rs-epub3-mp3-aac

It was the support box at the start of the media overlays section that was incorrect.

But after the merge of #1993, we now have contradictory statements going the other way: one conditional on supporting audio playback and the other not.

I would personally remove the support statement from 2.4, since it's not specific to core media types. But the support statement at the beginning of the MO section should also be clear that it's a recommendation when audio playback is supported. Otherwise, it's kind of weird to blanket recommend support when a device can't render audio.
