### ISSUE TITLE
Clarify that resources must be present for relative paths

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2024]
It appears in our rewrite of URL processing that we've lost the requirement for there to be a resource at the end of relative paths. In 3.2, we had this statement:

> All relative IRI references MUST resolve to resources within the OCF Abstract Container (i.e., at or below the Root Directory).

This was meant to cover both that the URL not leak outside the container and that there must be a resource at the end of it.

Our new rewrite covers URLs not leaking outside the container better, but we no longer appear to have a requirement that there be a resource at the destination. Without that bit, someone could argue that missing resources in the container aren't really errors.

We should add back a statement about the need for a resource to be present so that we're consistent again with previous versions of EPUB 3.

**Comment by OriKuttner** [comment]
I agree, we must not create a situation where a resource does not have to
be present.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by rdeltour** [comment]
I'm wondering if a SHOULD wouldn't be enough here now. For instance if an image is missing, I'd like EPUBCheck to warn me, but my EPUB isn't critically unreadable either. 🤔

**Comment by mattgarrish** [comment]
> I'd like EPUBCheck to warn me, but my EPUB isn't critically unreadable either

I get your point, but that can get highly subjective. If it's the cover or some decorative image, sure, but what if it's a key diagram in a science textbook?

Or, worse, a whole missing content document?

Do we start enumerating what elements a missing resource is an error from? That sounds brittle.

**Comment by OriKuttner** [comment]
I agree with Matt, if we say missing resource is a warning, we might get
publications with key diagrams missing.
So it should be a MUST, not SHOULD.

**Comment by rdeltour** [comment]
For reference, a pointer to previous discussion about that in https://github.com/w3c/epub-specs/pull/1939#discussion_r761885322 (starting with "Also, a side comment not specific to the current PR" and following comments).

**Comment by OriKuttner** [comment]
I think we should discourage URL's that point to resources outside the
publication, but for resources inside the publication, all of them must
exist.
We can warn on referencing for example:
https://www.example.com/files/image1.jpg
But similar URL such as /images/image1.jpg if the resource is missing this
is an error.
I am not sure how to phrase it but I guess you get the point.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-03-03-epub#section3) on 2022-03-03

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-03-03-epub#resolution2):  Merge PR 2028, close issue 2024.***

<details><summary><i>View the transcript</i></summary>

### 3. Clarify that resources must be present for relative paths (issue epub-specs#2024)

_See github issue [epub-specs#2024](https://github.com/w3c/epub-specs/issues/2024)._




**Dave Cramer:** Our other issue is similar. When we did this we lost a requirement that there be a resource at the end of the path.  
… originally we had 1. not leak and 2. must exist.  

_See github pull request [epub-specs#2028](https://github.com/w3c/epub-specs/pull/2028)._




**Dave Cramer:** We lost part 2. We should put it back. There is already a PR.  

**Matt Garrish:** We just need to put the existence text back.  

**Dave Cramer:** Yes, and it sounds like the PR does just that.  
… I am in favor of merging.  

**Dan Lazin:** I don't know if it follows that there must always be a thing that is referenced.  
… For instance a book on how to write epub that shows errors (eg this is what it looks like when a resource is missing).  
… The cases are rare, but I can imagine some.  
… and there are plenty of ways to create bad content.  

**Wendy Reid:** Going with must on this, because nothing stops people from ignoring epubcheck.  
… In general epubcheck is heavily relied on by publishers to tell them of problems.  
… and this will more often than not help those publishers find problems.  

**Matt Garrish:** I basically agree with wendyreid.  
… epubcheck does look for this now.  
… There are other things epubcheck will flag.  
… This seems like a can of worms to change, and error has worked really well to date.  

**Dan Lazin:** Those are persuasive arguments.  
… I thought epubcheck gave warnings on shoulds, isn't that good enough?.  

**Wendy Reid:** Errors scare them more.  

**Dan Lazin:** I am ok with must, but odd that epubcheck is preflight and a conformance checker.  

> **Proposed resolution: Merge PR 2028, close issue 2024.** *(Wendy Reid)*

**Dave Cramer:** Propose merging 2028.  

> *Dave Cramer:* +1.

> *Matt Garrish:* +1.

> *Dan Lazin:* +1.

> *Shinya Takami (高見真也):* +1.

> *Brady Duga:* +1.

> *Wendy Reid:* +1.

> *Zheng Xu (徐征):* +1.

> *Toshiaki Koike:* +1.

> ***Resolution #2: Merge PR 2028, close issue 2024.***

**Dave Cramer:** AOB?.  

</details>
