### ISSUE TITLE
Is nav hidden attribute guidance non-normative?

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2061]
I'm failing to see how [this section](https://www.w3.org/TR/epub-33/#sec-nav-def-hidden) is even specific to the navigation document, let alone normative.

All it says is to control rendering of the nav elements in the spine in reading systems without a viewport, use the `hidden` attribute because CSS won't be as reliable. (The "must" is unenforceable.)

But by the same logic, if you want to control rendering of any HTML content in the spine in a reading system without a viewport you should use the `hidden` attribute.

It seems like this might almost slot in better as an informative section under CSS.

**Comment by iherman** [comment]
I agree that there is no reason this section is normative; it just reinforces the usage of an existing HTML mechanism. 

I am actually not sure I understand the statement:

> While the [display property](https://www.w3.org/TR/CSS2/visuren.html#propdef-display) [[CSSSnapshot](https://www.w3.org/TR/epub-33/#bib-csssnapshot)] controls the visual rendering of EPUB Navigation Documents in Reading Systems with [Viewports](https://www.w3.org/TR/epub-33/#dfn-viewport), not all Reading Systems provide such an interface.

what is the problem here? I have never met any problems with the display attribute, certainly not with the base usage of the `none` value (which would be the one to be used for the purpose described in the section). I also do not really understand the reference to the viewport here.

Actually... the usage of the `hidden` attribute maybe a bit iffy for the purpose described here. Looking at the [HTML spec](https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute), it says:

> The [hidden](https://html.spec.whatwg.org/multipage/interaction.html#attr-hidden) attribute must not be used to hide content that could legitimately be shown in another presentation. [...] It is similarly incorrect to use this attribute to hide content just from one presentation — if something is marked [hidden](https://html.spec.whatwg.org/multipage/interaction.html#attr-hidden), it is hidden from all presentations, including, for instance, screen readers.

One could argue that the usage of the nav content for the RS TOC is not a presentation, because the structural information is used instead of the HTML rendering, but it may raise eyebrows nevertheless.

On the other hand, the goal described in the section is a legitimate use case. Maybe it is better to

- rename the section to explicitly refer to the nav use case, something like "hide parts of the navigation data within the content flow"
- making it informative
- the content should simply say that the CSS display attribute is a good tool to achieve the goal (and probably preferred) but making it clear that, if interoperability with legacy RS-s is required (a phrase we already use elsewhere in the document) use the `hidden` attribute
- keep the examples

**Comment by mattgarrish** [comment]
> I have never met any problems with the display attribute, certainly not with the base usage of the `none` value (which would be the one to be used for the purpose described in the section).

In reading systems without a viewport? (e.g., one that only TTSes the text, as these do exist in the accessibility space)

CSS support isn't required and most likely won't be available, so I understand why the guidance is there. I just don't see it as normative or specific to tables of contents.

I agree with your first, second and fourth bullets, in other words.

> Actually... the usage of the `hidden` attribute maybe a bit iffy for the purpose described here.

Ya, that's always been a bit if a grey area. The RS rendering of the toc isn't an HTML "presentation" in most cases, but a harvesting of information to present in a completely different form. It's not a violation in that respect. But there are reading systems that operate in browsers and would have to strip the hidden attributes as part of displaying the toc. That's the more problematic use, but it was a willful violation on our part as far as I remember.

But it's also too late to change the RS behaviour now. It would make a big mess of existing content if reading systems were to respect the attribute in their own presentations.

It's no doubt also part of why authors do separate tables of contents for the nav doc and spine.
