### ISSUE TITLE
File names and file paths are confusing

### ISSUE THREAD

**Issue by murata2makoto** [mattgarrish/epub-revision#2078]
EPUB 3.3 uses all of "resource", "file", and "directory".  Here "resource" comes from the URL world, while "file" and "directory" come from operating systems.  The status quo might not be ideal, but I think that this is the way it is.

However, I am not happy with "file name" and "file path".  First, they are used for directories as well as files.  I think that this is highly confusing.  Second, they do not fit in the URL terminology well.  As a result, it is not obvious whether file paths are allowed as part of URLs.  Note that "file name" and "directory" never appear in the WHATWG URL specification.

I thus propose to reformulate Section 6 of EPUB 3.3 by avoiding these terms.  Since "file name" and "file path" do not appear so often, such reformulation is not difficult.

Here is one way to reformulate Section 6.

First, we use "URL-path-segment string" rather than "file name" (see https://url.spec.whatwg.org/#url-path-segment-string).  Within a directory, every file and subdirectory is uniquely identified by a URL-path-segment string such that (1) it is not a single-dot path segment, (2) it is not a double-dot path segment, and that (3) it is a sequence of URL units satisfying the constraint in Section 6.1 (Note: Here I assume that percent-encoded characters satisfy the same restriction.)

Second, we use "path-absolute-URL string" rather than "file path" (see https://url.spec.whatwg.org/#path-absolute-url-string).  The algorithm in Section 6.1.4 (with the addition "/" at the beginning) can be used to construct a "path-absolute-URL string" from a file.

Alternatively, we might want to begin with our own restrictions on code units.  Given a URL, we parse it and then get a path-absolute-URL string from the parsing result.  The path-absolute-URL string references a file or directory in our virtual file system.

**Comment by mattgarrish** [comment]
The OCF Abstract Container is a virtual file system, so talking about URL strings in place of file names and paths doesn't sound like it will reduce confusion. It probably only makes the section more difficult to understand.

While the restrictions will also impact on the URL representataions of the file names and paths, that's not what is primarily being talked about in section 6. Doesn't 6.1.5 already handle the implications for URLs?

**Comment by iherman** [comment]
@mattgarrish wrote:

> The OCF Abstract Container is a virtual file system, so talking about URL strings in place of file names and paths doesn't sound like it will reduce confusion. 

actually, that would increase the confusion in my view. 

The core of our problem is that an EPUB instance is a slightly schizophrenic beast: it is a (virtual) file system and, at the same time, it is also to be represented as a (virtual) Website, because all our structure relies on Web technologies. The specification is complex because we have to formally define a "bridge" between these two worlds which, though similar, are not identical. The problem of percent encoding is a typical example for the discrepancies.

As a consequence, using "URL-path-segment string" for file names would be conceptually wrong.

@murata2makoto you also wrote

> Note that "file name" and "directory" never appear in the WHATWG URL specification.

And that is the way it must be. The URL specification only looks at one aspect of the aforementioned two worlds, namely a virtual model of a Website through URLs; it does not define how a Web server like Apache realizes that model. Our problem is that we also have to define that aspect because we do define OCF to exchange such underlying file structure.

I do agree that it is a bit misleading that the term "File Name" can refer to a directory or a (traditional) file. Although this is current practice in many programming environments (e.g., the same 'name' is used to access both a file or a directory in, say, the file system access API in the core Unix libraries) it may be misleading for the casual reader. I remember we considered using a term like "File or Directory Name" but it does look overly complex. Nevertheless, I would be open to rename the term (it appears 8 times in the spec, aside from the section title and terminology section).

**Comment by murata2makoto** [comment]
Do file paths and file/directory names appear in EPUB publications or URLs?  In my understanding, they don't.  The result of translating them to the URL world does.  If the name of a file is "A%2FB" (using the example in #2077), "A%2FB" doesn't occur in EPUB publications or URLs for referencing this file.  "A%252FB" does.

But if I am not mistaken, there is an exception.  "A%2FB" occurs in ZIP headers for this file.

I thought that the virtual file system is more virtual and wanted to avoid it.  But it appears that both the virtual file system and the virtual Website are equally real.  ;-(

>The core of our problem is that an EPUB instance is a slightly schizophrenic beast: it is a (virtual) file system and, at the same time, it is also to be represented as a (virtual) Website, because all our structure relies on Web technologies. The specification is complex because we have to formally define a "bridge" between these two worlds which, though similar, are not identical. The problem of percent encoding is a typical example for the discrepancies.

I now understand and agree.  But understanding this big picture is hard.

**Comment by iherman** [comment]
> 
> I thought that the virtual file system is more virtual and wanted to avoid it. But it appears that both the virtual file system and the virtual Website are equally real. ;-(
> 
> > The core of our problem is that an EPUB instance is a slightly schizophrenic beast: it is a (virtual) file system and, at the same time, it is also to be represented as a (virtual) Website, because all our structure relies on Web technologies. The specification is complex because we have to formally define a "bridge" between these two worlds which, though similar, are not identical. The problem of percent encoding is a typical example for the discrepancies.
> 
> I now understand and agree. But understanding this big picture is hard.

Yes, it is. 

After this discussion... I wonder whether we should not add an explanation on the whole area into the [Overview](https://www.w3.org/TR/epub-overview-33/#sec-package-file) document. I think we may agree that the _specification_ text is correct as is, it is just difficult to grasp; the Overview document may be the good place to help the readers.

WDYT?

(The good thing is that the Overview document is a Note. We can get into improving it when we are in CR...)

**Comment by mattgarrish** [comment]
> I thought that the virtual file system is more virtual and wanted to avoid it.

But you can't from the perspective of putting things into a ZIP container, which is what s. 6 is primarily about. The restrictions are about representing the resources in the ZIP, not about how they will later get rendered. The container is "storing" the file system of the publication, in a sense.

That's why I'm not sure I see the issue in terms of how the section is currently phrased. You are creating file paths in the ZIP archive and we are stating the restrictions on them. It's not a "real" file system inside the ZIP, but it becomes that from the perspective of the reading system, whether by unpacking or handling requests into the ZIP.

There are considerations relative to how the content later gets displayed, which as already noted is more like a website, but I don't see that as confusing to understand. That;'s like saying it's confusing to FTP my files to a server because in the HTML I have to reference them using URLs. Or that we need to stop talking about the files on the server as a file system because how they're rendered on the web has different restrictions.

If your idea @iherman is to make more explicit how OCF is like a web server representation in the Overview, so the directory model has similar constraints, that's fine with me.

**Comment by iherman** [comment]
> If your idea @iherman is to make more explicit how OCF is like a web server representation in the Overview, so the directory model has similar constraints, that's fine with me.

Yes, something like that.

**Comment by murata2makoto** [comment]
@mattgarrish 

> You are creating file paths in the ZIP archive and we are stating the restrictions on them. It's not a "real" file system inside the ZIP, but it becomes that from the perspective of the reading system, whether by unpacking or handling requests into the ZIP.

Yes, this is what I meant by "But if I am not mistaken, there is an exception. "A%2FB" occurs in ZIP headers for this file."

@iherman 

>After this discussion... I wonder whether we should not add an explanation on the whole area into the [Overview](https://www.w3.org/TR/epub-overview-33/#sec-package-file) document. I think we may agree that the specification text is correct as is, it is just difficult to grasp; the Overview document may be the good place to help the readers.

That is a good thing to have.

I am also wondering if introducing your example in the spec would help.

- "A%2FB":   the parameter "file name" in the local file header or central directory header in a ZIP file
- "A%252FB": the href attribute of an item element in an OPF file

**Comment by iherman** [comment]
> I am also wondering if introducing your example in the spec would help.
> 
> * "A%2FB":   the parameter "file name" in the local file header or central directory header in a ZIP file
> * "A%252FB": the href attribute of an item element in an OPF file

There is already a note on the fact that the space character is replaced by %20 in the URL. That is a usual use case, because many people use space characters in file names (I know I do it a lot for my own files on my laptop). But, frankly, I have never seen any example of somebody using percent encoding a character like '/' into a file name. The whole notion of percent encoding is unknown in a system like Linux or MacOS (I suspect it is the same for Windows), ie, it is not something a user would ever do. In other words, I would find this example to be very artificial in the spec...

**Comment by murata2makoto** [comment]
Ah, %20 is certainly much better.  

I had a look at the note you mentioned.  I might be insane but I feel comfortable only when I see "A/B/C/file name.xhtml" in the ZIP file.  I did create an EPUB file containing "st 1.opf" as the OPF file and made sure that the hexadecimal dump of the zip file does have "st 1.opf" in a local file header.
