### ISSUE TITLE
Missing CSS values

### ISSUE THREAD

**Issue by bduga** [mattgarrish/epub-revision#2153]
Not all CSS values are listed in the section of prefixed CSS properties. I am not sure if that is expected or not, but it does seem confusing. We should either mention that, or extend to include all values. For instance, text-underline-position does not mention `from-front`.

**Comment by mattgarrish** [comment]
From what I found, `from-font` is only defined in [CSS Text Decoration Module Level 4](https://www.w3.org/TR/css-text-decor-4/#text-underline-position-property).

Since we only reference Level 3, I'd say it's out of scope.

**Comment by mattgarrish** [comment]
There are a number of other differences between our definitions and the CSS specs, though:

- -epub-text-orientation: sideways-right is accepted as a keyword but maps to sideways
- <strike>-epub-line-break is missing "anywhere"</strike>
- <strike>-epub-text-align-last is missing "match-parent"</strike>
- -epub-word-break is missing "break-word" although this is deprecated in css (maybe this should be noted like the removal of the "all" property?)
- -epub-text-emphasis-position is missing the optional ? indicator after [right | left]

**Comment by mattgarrish** [comment]
And I just spotted this note after the caution in the body section: https://www.w3.org/TR/epub-33/#h-note-38

Might be better to have this lead in to the appendix. That strikes out a couple of the issues I spotted.

**Comment by mattgarrish** [comment]
I hate wading into the evolution of prefixed/unprefixed properties, but can we say we're not continuing to map new additions and you should not use the prefixed versions for them, at least as a note?

I'm thinking we take the note from the body and modify it as follows to preface the appendix:

> The prefix definitions are no longer being synchronized with their CSS counterparts. In some cases, the unprefixed versions of these properties now support additional values. Reading Systems may not support the new syntaxes with the prefixed properties, so EPUB Creators are advised to use the unprefixed versions for newer features.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-04-08-epub#section2) on 2022-04-08

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-04-08-epub#resolution2):  Adopt the recommended text in issue 2153, close issue.***

<details><summary><i>View the transcript</i></summary>

### 2. Missing CSS values (issue epub-specs#2153)

_See github issue [epub-specs#2153](https://github.com/w3c/epub-specs/issues/2153)._




**Dave Cramer:** this refers to our appendix documenting epub's prefixed CSS properties.  
… original intent was to document what epub had and how that related to the current state of CSS, but we did not exhaustively document all modern CSS properties with epub equivalents.  
… there was a suggestion in the issue, and I have no objection to that.  
… mgarrish had sample text in issue.  
… "The prefix definitions are no longer being synchronized with their CSS counterparts. In some cases, the unprefixed versions of these properties now support additional values. Reading Systems may not support the new syntaxes with the prefixed properties, so EPUB Creators are advised to use the unprefixed versions for newer features.".  
… seems like good advice.  

**Matt Garrish:** avoids wg having to maintain this section going forward.  

**Dave Cramer:** we'd have to reference various different CSS modules in the appendix to our spec, not the goal.  

**Ivan Herman:** does this modify the existing CSS tests that wendyreid made? Does it require new tests?  

**Dave Cramer:** I don't think so.  

> *Murata Makoto:* Agreed.

**Matt Garrish:** we're testing what was already there, but we're not testing what has been added to CSS since the prefixes.  

**Ivan Herman:** okay, good with me.  

**Dave Cramer:** i don't think we should test using a new value in a epub prefixed property.  

**Matt Garrish:** I'll create PR that just implements that text from the issue.  

> **Proposed resolution: Adopt the recommended text in issue 2153, close issue.** *(Wendy Reid)*

> *Murata Makoto:* +1.

> *Matt Garrish:* +1.

> *Ivan Herman:* +1.

> *Wendy Reid:* +1.

> *Matthew Chan:* +1.

> *GeorgeK:* +1.

> *Dave Cramer:* +1.

> *Bill Kasdorf:* +1.

> *Shinya Takami (高見真也):* +1.

> *Masakazu Kitahara:* +1.

> *Ben Schroeter:* +1.

> ***Resolution #2: Adopt the recommended text in issue 2153, close issue.***

</details>
