### ISSUE TITLE
Clarify rendering optimization

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2159]
I don't understand what this means:

> Reading Systems MAY optimize the rendering depending on the properties set in the properties attribute (e.g., disable a rendering process or use a fallback).

https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-manifest

Can you clarify? An example of a property might help here. Also, I don't understand why this needs to be in the spec at all — isn't optimization an internal concern of the RS? Particularly given that this is a MAY, I wonder if it should just be cut.

**Comment by mattgarrish** [comment]
> An example of a property might help here.

Say you have this:

```
<item href="widget.xhtml" ... properties="scripted" fallback="unscripted"/>
```

A reading system could use the info that the document is scripted to enable scripting -- some block all scripting by default, and only turn it on selectively -- or it might choose to use the fallback if it doesn't support scripting.

> I don't understand why this needs to be in the spec at all — isn't optimization an internal concern of the RS?

Yes, but I expect it was also meant to be instructive about why we created the attribute.

It's probably not necessary anymore now that we have a dedicated section explaining the properties attribute in the core spec: https://w3c.github.io/epub-specs/epub33/core/#sec-item-resource-properties

**Comment by iherman** [comment]
Whilst removing that sentence is probably o.k. (let alone the fact that fallbacks are, shall we say, iffy in terms of implementations in general), I think adding a link to the section on properties may be useful. There is one in the third paragraph, but may be better having a link on the first occurrence.

**Comment by mattgarrish** [comment]
> let alone the fact that fallbacks are, shall we say, iffy in terms of implementations in general

I don't know that the attribute is used at all for fallbacks. It's a theory, even more than fallbacks themselves.

What it has been stated to be used for in the past is turning on scripting, enabling mathjax rendering (which would otherwise be expensive to always run), finding the cover image to use as a splash screen, and those kinds of internal rendering optimizations.

But we don't need to say all the things reading systems may do with metadata, especially when the authoring section so clearly lists these. Links are always good!

**Comment by iherman** [comment]
@dlazin @mattgarrish #2195 has been created for this.
