### ISSUE TITLE
Note on container root URL implies inconsistent /EPUB/ folder

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2168]
This might be correct, but looks questionable to me. The (long) second note at https://w3c.github.io/epub-specs/epub33/rs/#sec-container-iri shows these examples:

Container File | File Path | URL
-- | -- | --
Root Directory | empty string | http://localhost:49152/
Package Document | EPUB/package.opf | http://localhost:49152/EPUB/package.opf
Content Document | HTML/file name.xhtml | http://localhost:49152/HTML/file%20name.xhtml

URL string(found for example in the package document) | Content URL
-- | --
../HTML/file%20name.xhtml | http://localhost:49152/HTML/file%20name.xhtml
/Media/img.png | http://localhost:49152/Media/img.png
../../../Media/img.png | http://localhost:49152/Media/img.png

Observe that the Package Document is in /EPUB/ (usually a placeholder for the content directory that is an arbitrarily named peer of /META-INF/).

By contrast, the other examples do not include /EPUB/.

I would expect to see either `http://localhost:49152/EPUB/HTML/file%20name.xhtml` (adding /EPUB/ to all content files) or `http://localhost:49152/package.opf` (no /EPUB/ there either).

Am I wrong?

**Comment by mattgarrish** [comment]
> Observe that the Package Document is in /EPUB/

The directory the package document is in is not the root of the container. It's technically as irrelevant as any other directory in the container.

The root is the zip/container root, so if the package document is in an /EPUB subdirectory (or /HTML), there is a directory above that any resource can reference up to.

_But_ where things get confusing is that the container root isn't always preserved when extracting a publication, so sometimes the directory the package document is in does get treated as the publication root. That's why you can't reference across to sibling directories on some reading systems. (In that case, there still isn't /EPUB in the resolved URL, as /EPUB is the root.)

The examples are describing how relative paths are resolved relative to the container root, though, so that's why the results are the way they are. The package document can reference one level up to the root directory and then down into the HTML directory, for example, which is why `../HTML/file%20name.xhtml` becomes `http://localhost:49152/HTML/file%20name.xhtml`. (Similarly, you could have a reference in your HTML file like '../HTML/xyz.jpg' as this just goes up a level and then back down into the same directory.)

Not anchoring the package document as your root may not work on every reading system, in other words, but having references that reach up to the container root is perfectly valid from a container processing perspective.

**Comment by dlazin** [comment]
If this is totally valid, then you can close this issue. I'm accustomed to seeing something more like this structure:

/EPUB/package.opf
/EPUB/HTML/chapter1.xhtml
/EPUB/IMG/image1.png

But if those other files are all allowed to be in peer directories, then cool, no problem with the spec.

**Comment by mattgarrish** [comment]
> I'm accustomed to seeing something more like this structure:

Right, this is what you'll find in most EPUBs as it's generally what authoring tools spit out. It also works on the most reading systems, so is the best way to do it. But it's not a requirement.

Even a structure as dumb as the following is valid:

```
/mimetype
/META-INF/container.xml
/OPF/package.opf
chapter1.xhtml
IMG/image1.png
```

We warn about the problem this kind of structure can cause in the multiple renditions spec, as that's where sharing directories really exposed the issue: https://www.w3.org/TR/epub-multi-rend-11/#h-note

**Comment by iherman** [comment]
@dlazin the impression you get is, afaik, due to a strange copy-paste effect. @mattgarrish has been around way earlier than I was in this world, but it seems that some earlier RS implementations were buggy in the sense that they expected a particular file system organization, which was then followed by all EPUB examples, and this led to the belief that such an organization is what the standard requires.

Actually... afaik, there are still some RS-s that do not implement correctly the file system and, again afaik, we do have tests that should reveal that. (To be checked...). In this respect it is actually a good thing if the standard does include examples that are, in this respect, unusual...

Closing the issue...

**Comment by mattgarrish** [comment]
> but it seems that some earlier RS implementations were buggy in the sense that they expected a particular file system organization, which was then followed by all EPUB examples

I don't know that it evolved this way. In my experience, the practice of content coming out in an "OEBPS" or "OPS" directory (going back to the old standards) came from InDesign, since that's what most publishers were using back in the day.

As far as examples, it's just a clean way to separate the content from the mimetype and META-INF files for explanation purposes. It works with the idea that you can author a publication as an HTML site in a single folder and then wrap it up in the OCF container (or turn it around and unpack it).

I would argue the resulting divergence in what reading systems do is based on a combination of the spec not being clear and reading systems subsequently making their own interpretations.

To me, the lack of clear direction about why the container root is optional to preserve is root of all evil here. I'm not sure how you're going to prove that a reading system that doesn't allow access to content in sibling directories is invalid. Where do we say that links/references must work no matter whether you preserve the container root or not? We only ensure content is consistent within the concept of the abstract container.
