### ISSUE TITLE
Normative MUST for name-change compensation?

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2170]
https://w3c.github.io/epub-specs/epub33/rs/#sec-container-filenames says:
> If a Reading System cannot preserve the names of files during an unzipping process, it will have to compensate for any name translation that took place in the content (i.e., in any URIs that reference the original name).

"it will have to" sounds like it oughta be a normative MUST.

I have not made this change in https://github.com/w3c/epub-specs/pull/2169, since it it substantial, not editorial.

**Comment by mattgarrish** [comment]
I don't have a definite answer for this one, but my expectation is that this has been informative because it's primarily an authoring problem.

We neither tell reading systems how to compensate for invalid characters nor require they process and correct publications on the fly. That would allow them to do the easier part of compensating for invalid file names while unzipping (to get some of the publication to work) while not bothering trying to process the markup to fix references/links.

Both this para and the one before can probably be merged into a note.

**Comment by dlazin** [comment]
My reading (so, if wrong, we should clarify this) is that this *is* a RS requirement. The previous paragraph says:

> This specification does not specify how a Reading System that is unable to represent OCF File Names and Paths would compensate for this incompatibility.

But I think (??) that this last paragraph is saying either of these two things:
a) this spec isn't saying *how* (previous paragraph) you compensate, but you must compensate somehow, or
b) this spec isn't saying whether/how you compensate for OCF filenames (that is, the core publication files), but it is saying the RS should compensate for document filenames while unzipping.

I guess, in short, I am confused :)

**Comment by mattgarrish** [comment]
> But I think (??) that this last paragraph is saying either of these two things:

The paragraphs never followed each other in the past; they only appear that way now from being pulled out from the core spec.

If you [go back to 3.2](https://www.w3.org/publishing/epub3/epub-ocf.html#sec-container-filenames), you'll find the first is related to the inability to represent file names on operating systems. The second came from the note about unzipping at the end of the section.

They're close enough in purpose that we could join them in a note, but I don't know that we'll get reading system developers to agree that they must compensate for naming problems or be responsible for modifying authors' content.

That's why there isn't a normative requirement, and one part has always been a note. If file names can't be represented on an operating system, then the publication is busted on that operating system and that's just the way it is.

What I'd say needs modification is the first paragraph to say:

> This specification does not specify how a Reading System that is unable to represent OCF File Names and Paths would compensate for this incompatibility, _if at all_.

But I'd be interested to hear how developers in the group have interpreted this.

**Comment by iherman** [comment]
I was not around in the old days, ie, I do not have the baggage of history. For my fresh view of an RS, the statement:

> This specification does not specify how a Reading System that is unable to represent OCF File Names and Paths would compensate for this incompatibility, if at all.

Indeed, if we put here a normative requirement for the RS then, in some sense, we would be getting into the detailed specification of how the RS should handle errors, i.e., nonconforming EPUB content. After the Core spec has a [detailed spec on file names](https://w3c.github.io/epub-specs/epub33/core/#sec-container-filenames), ie, the whole issue comes up with faulty EPUB content anyway. And we do not normatively specify error _behavior_ anywhere.

**Comment by dlazin** [comment]
I'm certainly OK with this not being normative (and with the spec not saying how to handle errors), but my reading is that the current text is telling RSes what to do (partially), just without a MUST. Should we remove the quoted section (in the initial report above) entirely?

**Comment by iherman** [comment]
My proposal is to remove the last paragraph of that section altogether. The previous paragraph can stay as is; because it just says what the spec does _not_ specify, it is not necessary to put it as a note.
