### ISSUE TITLE
Consider moving the OCF section earlier in the spec?

### ISSUE THREAD

**Issue by rdeltour** [mattgarrish/epub-revision#2177]
This is purely editorial, but I always find it odd that the OCF section sits between "Layout Rendering Control" and "Media Overlays". The container concept is quite central to EPUB, and introduces core notions like the file structure, URL parsing, etc. I would put it either before "EPUB Publications", or right after it.

I hesitated to file this, but thought that if we ever want to touch this, better do it before CR. Feel free to disregard if it's too late or just fine as is 😊.

**Comment by iherman** [comment]
It makes sense to me (and no, it is not too late).

I do not remember how it landed there. I suspect this was done when the 3.2 documents were (re-)merged and then split in different ways without giving too much thoughts about the order (I do not remember thinking about at the time, at least).

**Comment by mattgarrish** [comment]
There was some method to the madness, but then along came privacy and security... and then we started destructuring...

The "core" was (going back to earlier efforts to make the spec whole) what was in EPUB 3.2, Packages 3.2, Content Docs 3.2 and OCF 3.2.

Packaging being the last thing you usually do, and being sort of a format unto itself, it's always been slotted in last. That was how I originally merged the specs (one major section for each), with Media Ovlerays falling after because it's optional technology (I may not have even had it in the first merge attempt).

The argument about where it best fits could go either way. Should it still logically follow everything about putting an EPUB together, or should it go higher? Are we going to bash people over the head with dense technical packaging considerations before they even know what goes in a publication? (The density of OCF has always made it the most unloved spec of all.)

**Comment by dlazin** [comment]
+1. You can see the order I decided on for the MDN docs here:
https://github.com/dlazin/mdn-yari/blob/main/kumascript/macros/EPUBRef.ejs

I put OCF up much higher there for the same reason.

**Comment by mattgarrish** [comment]
If we move OCF up we either have to blow up section 2 (in whole or part) or slot it after.

If we slot it after, then the package document would need to move up to a top-level section (which is how it used to be when it was ported over to represent Packages 3.2).

So option 1 would be to keep section 2 partially intact:

```
2 EPUB Publications
2.1 Conformance Criteria
...
2.2 Publication Resources
...
3 Open Container Format
...
4 Package Document
...
5 EPUB Content Documents
```

While option 2 could be to lose s.2 entirely:

```
2 EPUB Publications Conformance
...
3 Publication Resources
...
4 Open Container Format
...
5 Package Document
...
6 EPUB Content Documents
```

I lean toward this latter option.

**Comment by iherman** [comment]
I agree with option 2. It is true that the current section 2 (conformance criteria, publication resources, package document) has become a strange beast compared to the granularity of the other sections (epub content documents, navigation document, etc.).

+1 to option 2, thus.

**Comment by rdeltour** [comment]
Both options look OK to me. I like that the package document gets its own top-level section.
