### ISSUE TITLE
Proposal for a new plane: Local or Remote

### ISSUE THREAD

**Issue by murata2makoto** [mattgarrish/epub-revision#2194]
Some resources are local (i.e., located inside the EPUB Container) while others are remote (i.e., outside of the EPUB Container).  In my understanding, local/remote is orthogonal to the manifest plane, spine plane, and content plane.  I thus propose to add the distinction of local and remote as another plane.

**Comment by iherman** [comment]
All other planes have an effect on the behaviour of a specific resource and the validity of the EPUB Publication itself. Ie, they play a role on the way the specification is built. What would the local/remote plane bring to the spec? What types of validity requirement does it influence. I may very well miss something, but I do not remember there is any...

**Comment by murata2makoto** [comment]
>What would the local/remote plane bring to the spec? What types of validity requirement does it influence.

There is already a [subsection ](https://w3c.github.io/epub-specs/epub33/core/#sec-resource-locations)for this topic.  And it is not so easy to understand that the manifest plane and remote/local plane are orthogonal.  I think that it is better to explicitly introduce this plane.

**Comment by iherman** [comment]
Yep, you are right.

I am currently neutral whether to introduce a separate "plane" for that. @mattgarrish, what do you think?

**Comment by mattgarrish** [comment]
@dauwhe asked about this on the call, and, as you say, whether a resource is remote or not is a binary question. It's more like an adjective you can apply to certain publication resources (remote video, remote audio, etc.), not so much a different plane.

We do cover remote resources under what is called the "manifest plane" right now. This is why I was trying to hang other names on it, like "publication plane" and "container plane":

> [EPUB Creators](http://localhost:120/core/#dfn-epub-creator) always have to list these resources in the [manifest element](#sec-manifest-elem) but they do not have to locate them all in the [EPUB Container](#dfn-epub-container). EPUB 3 allows [audio, video, font and script data resources](#sec-resource-locations) to be hosted outside the Container.

In the end, I gave up on the need for another plane for the reasons I already mentioned and went with this text. Could we just elaborate more on remote/local within the manifest plane rather than try to create something new?

Creating a plane for this is making a very fine distinction, like saying we need a "flow plane" to differentiate content documents that reflow from content documents that are fxl, because that's arguably a more important part of the spec than allowing a few resources to live outside the container. Or that we need a scripting plane because we also talk about that far more, too. This path may lead us back to a model that strives for absolute technical precision at the expense of being comprehensible, which is the only goal of an introduction.

Assuming we add a new plane, what do we call this plane and what makes it more than a simplistic restatement of the remote resources definition?

**Comment by lordt4ever** [comment]
On me

**Comment by mattgarrish** [comment]
Looking at the specs, "remote resources" has become something of a mess.

It was originally supposed to define the exempt resources we allow outside the container, but somehow it morphed into also being used to talk about web sites and things that an `a` element can link to on the web. It looks like this was done for the nav document to allow it to link out to the web.

The only normative statement about remote resources appears to be that they are not guaranteed to be retrieved by reading systems. I'm wondering if we can inline the term in the resource location section, as in all cases the definition is unhelpful and you end up having to read that section to figure out what the term actually means.

There are more requirements on "local resources", but still very few overall. We could probably just describe these as "Container Resources" and define the term in the locations section.

If nothing else, I'm going clean this up when I have a minute.

But the misapplication of "web stuff" as "remote resources" does make me think there should be more about this in the introduction. I'm still not convinced it warrants a new "plane", though. If someone wants to propose a new name for this plane that is as easy to understand as the others, that would be a good starting point.

"container plane" is too small in scope, since that only covers one aspect of the plane. "location plane" is just plain weird...

**Comment by murata2makoto** [comment]
The biggest reason I proposed this plane is possible misinterpretations of the manifest plane.  I first thought that this plane is a collection of local resources.  Another guy in JDC had the same misunderstanding.

It would be nice to add a note explaining that the manifest plane may contain remote resources.  But if we start to mention local and remote resources here, it is better to introduce a new plane.
