### ISSUE TITLE
Use respec's xref feature

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2207]
Right now we have a script slurping the core document to get its definitions to add links from the other specs.

It looks like we could just export the definitions and use the xref feature in respec and dump the custom code.

**Comment by iherman** [comment]
Here is what I found out so far:

We have to add

```
xref : {
    profile: "web-platform",
    specs: ["epub-33", "epub-rs-33","epub-a11y-11"]
},
```

To `respecConfig`, and add a `class="export"` to all our `<dfn>` statements.

This should allow writing something like `[^nav^]` instead of `<a data-cite="html#the-nav-element">nav</nav>`, and the same for all of html, url, etc, and our own definitions. (Which is a big plus!) It is also possible to say `[= nav | the nav element =]` to make the reference different.

B.t.w., https://respec.org/xref/ is our friend to find the existing references...

Caveat: the resulting reference to, say, `nav` looks like this:

`<p><code><a data-type="element" href="https://html.spec.whatwg.org/multipage/sections.html#the-nav-element">nav</a></code></p>`

We will have to add to our style sheet a 

```
    code a {
        color: red !important;
    }
```

to get the red color that we have today, the current set up does not work.

Additional trick (not related to xref): it is possible to say `[[[HTML]]]`, which means that what is rendered is "_HTML Standard_" (with a link) instead of the `[[HTML]]`. It may make the document easier to read here and there.

**Comment by iherman** [comment]
Raised https://github.com/w3c/browser-specs/pull/581 to include EPUB and EPUB-RS into the list of specs that can be used directly via specref. (I did not add A11y because it does not seem to define terms of its own.)

**Comment by iherman** [comment]
See #2235 for exporting the EPUB terminology.
