### ISSUE TITLE
3.5.3 Evaluator Information in EPUB A11Y 1.1

### ISSUE THREAD

**Issue by murata2makoto** [mattgarrish/epub-revision#2217]
I think that [3.5.3 Evaluator Information](https://www.w3.org/TR/epub-a11y-11/#sec-conf-reporting-eval) says away too much that "any individual or party " can be a certifier and says too little about preferred certifiers.

Rather, I would like to see something like LIA as the first example.  In my understanding, LIA Is special as it is supported by publishers, accessibility organizations, and the government.   It would be nice if such desiderata can be mentioned as a note.  Does EAA say something about preferred certifiers?  (@gregoriopellegrino, what do you think?)

**Comment by clapierre** [comment]
My understanding is that LIA only certifies Italian trade publishers.
Now Benetech's "Global Certified Accessible" or GCA program has been certifying Publishers since the release of the Accessibility 1.0 specification here in the US, Canada, and expanding to parts of Europe and other countries as we continue to grow.  We currently have over 2 dozen publishers who have passed certification and are marking their content as passing the EPUB Accessibility1.0 specification.
Here are [our list of publishers who have already passed certification ](https://bornaccessible.benetech.org/certified-publishers/)and we are working with a dozen more who are at various stages of passing our program.

**Comment by mattgarrish** [comment]
The link in the first comment goes to the wrong section. It should go to https://www.w3.org/TR/epub-a11y-11/#sec-conf-reporting-eval

I'm wary of the specification preferring evaluators. I'm not even sure how we'd define what preferred means. The reason we have the note is because publishers didn't like the inference that they have to hire a third party to evaluate their content.

Maybe there's a middle road here where we acknowledge that there is a necessary skill set (and local authorities) without getting into preferences. So maybe modify the note along these lines:

> Any individual or party can perform a conformance evaluation provided they have the knowledge and tools to assess web content against the WCAG and EPUB requirements. Evaluators new to the field are encouraged to obtain any applicable credentials for their region to strengthen the confidence in their evaluations, but this is not a requirement.
> 
> Note that some regions designate a local authority responsible for all evaluations, however, in which case self-evaluation may not be sufficient.

**Comment by GeorgeKerscher** [comment]
I know of no jurisdiction that has a list of certified organizations.

**Comment by murata2makoto** [comment]
@mattgarrish 

Your note is an improvement, but I would like to further state that trust from society is critical.

**Comment by mattgarrish** [comment]
Let me look at the section again in the morning. It's not easy to read because of all the examples that intersperse the few paragraph of text. Maybe we can make a separate examples subsection, which would allow the credentials discussion to be grouped closer to the certifier. The message here is intertwined with both, as user trust is part of what credentials are meant to testify to.
