### ISSUE TITLE
Use lower case for references?

### ISSUE THREAD

**Issue by iherman** [mattgarrish/epub-revision#2251]
I really love the effect of #2250 (ie, #2135). I was wondering whether it is worth considering one step forward and use lower case references rather than uppercase ones. Ie, `[[html]]` instead of `[[HTML]]`. I always found that visually more pleasing than the upper case. I do not think there is an obligation to use upper case, see, eg, [the annotation model spec](https://www.w3.org/TR/annotation-model/#normative-references).

**Comment by mattgarrish** [comment]
> I was wondering whether it is worth considering one step forward and use lower case references rather than uppercase ones.

Worth trying again, at least. I tried this when we first converted to respec and it blew up a reference. I'm not 100% sure which, but I think it was if we used [html] we got the whatwg spec reference and if we used [HTML] we got the undated W3C reference from our biblio file. Because that's our most common reference, we kept them all uppercase to avoid the visual noise of going upper/lower depending on the reference. That's not an issue anymore, though.

But I'll take a copy of the references before making the change and compare it to what comes out after to make sure we don't get any unintended changes.
