### ISSUE TITLE
Index for spec?

### ISSUE THREAD

**Issue by dauwhe** [mattgarrish/epub-revision#2260]
In the EPUB 3.3 Webinar hosted by Booknet Canada, someone asked why the spec didn't have an index. It's a good question. I know that some other W3C specs do have indexes. Can ReSpec help with this?

**Comment by mattgarrish** [comment]
We [added one in 3.1](http://idpf.org/epub/31/spec/epub-spec.html#index) to account for having information spread across five specs, but it was removed earlier in this revision because it was a massive headache to maintain manually.

If you add an empty `<section id="index">`, respec will dump out a list of everything in `dfn` tags. Not sure how useful that is as an index, but it's an option.

**Comment by iherman** [comment]
Let us try to use the respec generated index. Now that we have extended the use of dfn-s to a number of terms that are not explicitly listed in the terminology section (xml elements) it may be useful. We can always remove it in the final spec if we feel it is useless...

**Comment by mattgarrish** [comment]
What I don't like is that it will expose the same problems we had exporting the terms - no context for which grammar elements belong to and missing elements because of dfn name collisions.

Even putting `data-dfn-for` on (if we ever get that working) doesn't make things any clearer. You just get two context-less links:

> - metadata
>   - [definition of](#dfn-metadata)
>   - [definition of](#dfn-metadata-0)

**Comment by iherman** [comment]
I have just run it locally and, though not perfect, it may still be useful. Some styling trick may be necessary to turn the code elements red as elsewhere in the document (`<a class="index-term" ...><code>...`) but I think it is useful to have it in the spec even though it may indeed be problematic here and there... And it really doesn't costs us a penny:)
