### ISSUE TITLE
Should the spec address links in referenced SVGs?

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2261]
The RS spec has a few references to hyperlinks and a few references to the difference between embedded SVGs (`<svg>`) and referenced SVGs (`<img src="....svg">`).

We also talk about navigating to external links: https://w3c.github.io/epub-specs/epub33/rs/#sec-epub-rs-external-links

However, I don't see, and I think I would expect to see (?), the following:

1) Clicking a hyperlink to a *content document* in an XHTML content document should navigate. This is obvious but doesn't seem to be stated. (We only talk about navigating in the spine, or external links.)

1) Clicking a hyperlink (to a content document or external link) in an *embedded SVG* should navigate.

1) Clicking a hyperlink (to a content document or external link) in a *referenced SVG* should ... do what? Nothing? It appears that Chrome does not navigate links in SVGs referenced from HTML pages, but I haven't researched.

**Comment by iherman** [comment]
I actually believe there is a fourth case, namely if one uses `object` rather than `img` to  refer to an SVG file. Your third point above would depend on this; hyperlinks from an SVG references via an `img` indeed does not activate, but it does when `object` is used. To make the statement complete, clicking a hyperlink in a referenced SVG via `object` should navigate.

**Comment by mattgarrish** [comment]
Maybe I'm not following the problem here, but aren't these issues for HTML/SVG user agents? There is a difference between a link that resolves internally and one that resolves externally for EPUB processing, but whether hyperlinks generally "work" are issues outside our scope of influence.

**Comment by iherman** [comment]
> Maybe I'm not following the problem here, but aren't these issues for HTML/SVG user agents? There is a difference between a link that resolves internally and one that resolves externally for EPUB processing, but whether hyperlinks generally "work" are issues outside our scope of influence.

You are probably right. Is it worth mentioning this in our spec (in a note)? It is indeed the source of confusion (even in browser land) and our constituency is less knowledgable than the browser power users

**Comment by mattgarrish** [comment]
Do you mean a general note that reading systems are expected to be conforming svg user agents, or are you looking to get into the details of link processing?

A general note could probably go in the relationship to svg section, as we point out that reading systems aren't necessarily conforming html user agents in the html section.

**Comment by OriKuttner** [comment]
On Wed, Jun 22, 2022 at 6:03 PM Matt Garrish ***@***.***>
wrote:

> Do you mean a general note that reading systems are expected to be
> conforming svg user agents, or are you looking to get into the details of
> link processing?
>
I think this is too ambiguous to write that RS should conform to SVG user
agent.
an RS is by itself a user agent isn't it?

**Comment by iherman** [comment]
> Do you mean a general note that reading systems are expected to be conforming svg user agents, or are you looking to get into the details of link processing?

Certainly the former.

> 
> A general note could probably go in the relationship to svg section, as we point out that reading systems aren't necessarily conforming html user agents in the html section.

+1

**Comment by iherman** [comment]
> I think this is too ambiguous to write that RS should conform to SVG user agent.

Well, an RS is already a conformant HTML user agent, isn't it? In practice, if an RS implementation relies on some WebView, this requirement would not be too ambitious.

Do I miss something?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-06-23-epub#section4) on 2022-06-23

List of resolutions:

- ***[Resolution No. 4](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-06-23-epub#resolution4):  Close issue 2261, won't fix.***

<details><summary><i>View the transcript</i></summary>

### 4. Should the specs address links in referenced SVGs?.

_See github issue [epub-specs#2261](https://github.com/w3c/epub-specs/issues/2261)._




**Dave Cramer:** we don't explicitly say what happens if you click a hyperlink in various different contexts, should we?  
… our special case is links from inside epub to outside, and we discuss that case.  
… for other contexts, that behaviour is covered by the appropriate spec.  

> *Brady Duga:* +1matt.

> **Proposed resolution: Close issue 2261, won't fix.** *(Wendy Reid)*

> *Brady Duga:* +1.

> *Wendy Reid:* +1.

> *Toshiaki Koike:* +1.

> *Shinya Takami (高見真也):* +1.

> *Matthew Chan:* +1.

> *Matt Garrish:* +1.

> *Dave Cramer:* +1.

> *Murata Makoto:* +1.

> *Masakazu Kitahara:* +1.

> ***Resolution #4: Close issue 2261, won't fix.***

</details>
