### ISSUE TITLE
no defined concept of related or unrelated documents

### ISSUE THREAD

**Issue by npdoty** [mattgarrish/epub-revision#2264]
In rs:
> Reading systems that allow users to store data MUST ensure they do not make that data available to other unrelated documents

I think "unrelated" is undefined; the spec makes clear that there isn't a reliable way to determine that documents are related. I think you just mean other documents.

**Comment by OriKuttner** [comment]
I think it can be unrelated publications or even other applications.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by mattgarrish** [comment]
> Reading systems that allow users to store data MUST ensure they do not make that data available to other unrelated documents

This text comes from way back when we did 3.0 and the security section said that "Reading Systems should behave as if a unique domain were allocated to each Content Document"

We updated the specification earlier in this revision to require allocating a domain (or creating equivalent separation) to each epub publication, as per-document isolation isn't terribly realistic, but it looks like this statement was overlooked.

We could modify it to say to not make the data available to other "epub publications", but that would seem to flow from having domain separation for each publication, since by nature you can't access storage across domains.

**Comment by iherman** [comment]
> We could modify it to say to not make the data available to other "epub publications", but that would seem to flow from having domain separation for each publication, since by nature you can't access storage across domains.

In my reading this means that the statement is superfluous anyway, because the situation may not arise in conformant RS-s? We could just remove the sentence then, or possibly add a note that this may not happen...

**Comment by mattgarrish** [comment]
> In my reading this means that the statement is superfluous anyway, because the situation may not arise in conformant RS-s?

Exactly, we'd just be restating an outcome of the domain-separation requirement.

The next sentence sounds equally weird now:

> In particular, checking for a matching document identifier (or similar metadata) is not a valid method to control access to persistent data.

If we feel it's important to call out, though, maybe we could just add a note that references the domain separation requirement?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-05-26-epub#section1-5) on 2022-05-26

List of resolutions:

- ***[Resolution No. 3](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-05-26-epub#resolution3):  Approve PR 2301, close issue 2264.***

<details><summary><i>View the transcript</i></summary>

#### 1.5. Persistent storage security.

_See github pull request [epub-specs#2301](https://github.com/w3c/epub-specs/pull/2301)._




_See github issue [epub-specs#2264](https://github.com/w3c/epub-specs/issues/2264)._




**Dave Cramer:** about unrelated documents.  

**Matt Garrish:** this is about two requirements that were still in the spec, but which are no longer applicable.  
… i.e., language around each document being treated as its own domain.  
… if you absolutely need to use persistent storage, then we recommend you encrypt instead of storing as plaintext.  

**Dave Cramer:** a lot of people have done proofs of concept of drafting epubs that can read data from local storage created by a different epub.  

**Matt Garrish:** not sure if javascript encrypting is trivial to break or not, but at least we are saying to pay attention to this.  
… we also recommend just not storing sensitive data in the first place, if you don't have to.  

> **Proposed resolution: Approve PR 2301, close issue 2264.** *(Wendy Reid)*

> *Dave Cramer:* +1.

> *Matt Garrish:* +1.

> *Brady Duga:* +1.

> *Shinya Takami (高見真也):* +1.

> *Wendy Reid:* +1.

> *Dan Lazin:* +1.

> *Toshiaki Koike:* +1.

> *Matthew Chan:* +1.

> *Masakazu Kitahara:* +1.

> ***Resolution #3: Approve PR 2301, close issue 2264.***

</details>
