### ISSUE TITLE
Unclear whether SVG dimensions only apply in fixed layout

### ISSUE THREAD

**Issue by dlazin** [mattgarrish/epub-revision#2270]
https://w3c.github.io/epub-specs/epub33/rs/#sec-fxl-dimensions is a subsection of Fixed Layout, and says:

> Reading systems MUST use the dimensions as defined in [Expressing the ICB in SVG](https://www.w3.org/TR/epub-33/#sec-fxl-icb-svg) [[epub-33](https://w3c.github.io/epub-specs/epub33/rs/#bib-epub-33)] to render [SVG content documents](https://www.w3.org/TR/epub-33/#dfn-svg-content-document).

This implies that SVG dimensions only must be respected for FXL publications, but since SVGs are images, I would think we expect reading systems to respect SVG dimensions — or at least *proportions* — in reflowable publications as well. Should we say something about this?

Similarly (?), it's unclear what a RS should do if a reflowable publication sets `viewport` dimensions for an XHTML document.

**Comment by iherman** [comment]
That is covered by the SVG spec, and I do not think we have anything to add in terms of normative statements in this spec. The behaviour is identical to how a browser an SVG document directly. (I am unsure whether we want to make a statement about it in the epub3 spec.)

The viewport dimension in an XHTML document have a meaning for CSS but, afaik, the relevant meta has never been defined formally in any HTML spec (if saw somewhere that it was originally an Apple meta for IOS devices). Our statement should be: we do not define it, and it is unpredictable what would happen... (ain't nice but that is what happens).

---

B.t.w., if you want to see how SVG defines what happens, you may want to look at the [preserveAspectRatio SVG attribute](https://www.w3.org/TR/SVG/coords.html#PreserveAspectRatioAttribute) on how the rendering happens. It is made even worse if the author uses the `x`, `y`, `width` and `height` attributes on the topmost svg element: in that case the image is in fixed dimensions, and the browser will clip it to its own display size...

**Comment by mattgarrish** [comment]
This is also a statement about creating the ICB. I fixed the wording for it in https://github.com/w3c/epub-specs/pull/2291

I don't think we need/want to say anything about rendering of non-FXL SVGs.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-06-23-epub#section3) on 2022-06-23

List of resolutions:

- ***[Resolution No. 3](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-06-23-epub#resolution3):  Close issue 2270, don't fix.***

<details><summary><i>View the transcript</i></summary>

### 3. Unclear whether SVG dimensions should only apply in FXL.

_See github issue [epub-specs#2270](https://github.com/w3c/epub-specs/issues/2270)._




**Dave Cramer:** in FXL stuff we say RS must use dimensions from ICB in rendering SVG documents. Do we respect SVG dimensions or at least proportions in reflow as well?  
… I think no.  

**Brady Duga:** agreed, this is for FXL section only.  

> **Proposed resolution: Close issue 2270, don't fix.** *(Wendy Reid)*

> *Dave Cramer:* +1.

> *Matt Garrish:* +1.

> *Wendy Reid:* +1.

> *Brady Duga:* +1.

> *Shinya Takami (高見真也):* +1.

> *Matthew Chan:* +1.

> *Toshiaki Koike:* +1.

> ***Resolution #3: Close issue 2270, don't fix.***

> *Murata Makoto:* +1.

> *Masakazu Kitahara:* +1.

</details>
