### ISSUE TITLE
Allocating bridgehead

### ISSUE THREAD

**Issue by dazrand** [mattgarrish/epub-revision#2327]
The bridgehead is defined as "A structurally insignificant heading that does not contribute to the hierarchical structure of the work."  Yet you can apply it on non-heading elements which may participate in the structure, but they won't set any hierarchy themselves. Should this semantic be limited to headings only?

**Comment by mattgarrish** [comment]
It should probably be deprecated. There's no such thing as a bridgehead in HTML so it only encourages bad authoring habits.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-06-23-epub#section1) on 2022-06-23

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-06-23-epub#resolution1):  Deprecate Bridgehead, close issue 2327.***

<details><summary><i>View the transcript</i></summary>

### 1. Allocating Bridgehead.

_See github issue [epub-specs#2327](https://github.com/w3c/epub-specs/issues/2327)._




**Dave Cramer:** someone is a little worried about how we defined `bridgehead` in the SSV.  
… i understand that using `bridgehead` won't have any impact on anything, and given that it doesn't exist in HTML, can we just deprecate it?.  

**Matt Garrish:** from an a11y perspective, people misunderstand these semantics. e.g. if they type a heading as bridgehead then they think it doesn't show up as a heading in AT.  

**Dave Cramer:** are we still making changes to the SSV?.  

**Matt Garrish:** we are publishing it as a note again.  

**Dave Cramer:** okay, in that case, yes, let's deprecate it.  

> **Proposed resolution: Deprecate Bridgehead, close issue 2327.** *(Wendy Reid)*

> *Dave Cramer:* +1.

> *Brady Duga:* +1.

> *Matt Garrish:* +1.

> *Shinya Takami (高見真也):* +1.

> *Wendy Reid:* +1.

> *Toshiaki Koike:* +1.

> *Matthew Chan:* +1.

> ***Resolution #1: Deprecate Bridgehead, close issue 2327.***

</details>
