### ISSUE TITLE
Clarify that the scheme attribute does not have a default vocabulary.

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2382]
It's the only attribute that requires a prefix for its values.

**Comment by iherman** [comment]
Indeed... I was surprised when I saw that in the PR on processing `property`, I didn't remember that particularity...

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-08-04-epub#section2) on 2022-08-04

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-08-04-epub#resolution1):  The WG supports merging #2379 pending approval from the assigned reviewers..***

<details><summary><i>View the transcript</i></summary>

### 2. Re-implement vocabulary association mechanisms as an algorithm (pr epub-specs#2379)

_See github pull request [epub-specs#2379](https://github.com/w3c/epub-specs/pull/2379)._




_See github issue [epub-specs#2378](https://github.com/w3c/epub-specs/issues/2378)._




_See github issue [epub-specs#2382](https://github.com/w3c/epub-specs/issues/2382)._




**Dave Cramer:** there are a couple issues associated with this (#2378, #2382).  
… this is very technical, I wish mgarrish were here to explain.  
… doesn't really seems to change how the spec works, more an editorial change.  
… seems like they were just looking for WG approval before merging, even though most of us probably won't have strong opinions on this.  
… i'm generally in favor of explaining things in an algorithmic fashion rather than hard to understand paragraphs.  
… maybe we just say that we don't have objection to merging this pending github reviews?.  

> **Proposed resolution: The WG supports merging #2379 pending approval from the assigned reviewers..** *(Dave Cramer)*

> *Dave Cramer:* +1.

> *Matthew Chan:* +1.

> *Brady Duga:* +1.

> *Toshiaki Koike:* +1.

> *Shinya Takami (高見真也):* +1.

> ***Resolution #1: The WG supports merging #2379 pending approval from the assigned reviewers..***

</details>
