### ISSUE TITLE
XML security risk: expansion of internal parsed entities

### ISSUE THREAD

**Issue by murata2makoto** [mattgarrish/epub-revision#2447]
RFC 7303 (XML Media Types) has a section ["Security considerations"](https://datatracker.ietf.org/doc/html/rfc7303#section-10),  The last paragraph is quoted below:

> Note that it is also possible to construct [XML](https://datatracker.ietf.org/doc/html/rfc7303#ref-XML) documents that make
>    use of what XML terms "[XML-]entity references" to construct repeated
>    expansions of text.  Recursive expansions are prohibited by [XML] and
>    XML processors are required to detect them.  However, even non-
>    recursive expansions may cause problems with the finite computing
>    resources of computers, if they are performed many times.  For
>    example, consider the case where XML-entity A consists of 100 copies
>    of XML-entity B, which in turn consists of 100 copies of XML-entity
>    C, and so on.

Note that such repetitive expansion of entities does not need external parsed entities (see #2433).   Internal entities can easily cause such expansion.  [entityExpansion.zip](https://github.com/w3c/epub-specs/files/9706493/entityExpansion.zip) contains two EPUB publications containing such internal parsed entities.  

One of them (IPAttackConformant.epub) conforms to EPUB 3.3.   This is because [3.9 XML conformance](https://www.w3.org/TR/epub-33/#sec-xml-constraints) in EPUB 3.3 does not prohibit internal parsed entities within internal DTD subsets.  Meanwhile, [3.6 XML processing](https://www.w3.org/TR/epub-rs-33/#sec-epub-rs-conf-xml) in EPUB 3.3 RS is silent about expansion of internal XML parsed entities.  Moreover, [5.1 Validating and Non-Validating Processors ](https://www.w3.org/TR/2008/REC-xml-20081126/#proc-types) in the XML recommendation requires that all conformant XML processors expand internal parsed entities declared in internal DTD subsets.  Thus,  EPUB 3.3 RS cannot prohibit the expansion of internal parsed entities.

The other EPUB publication in the ZIP file is derived from the first one, but its XHTML content documents contain DOCTYPE statements not allowed by 1[3.1.1 The DOCTYPE](https://html.spec.whatwg.org/multipage/syntax.html#the-doctype) in WHATWG HTML.

If the repetitive expansion of entities is a problem, an easy solution is to prohibit internal DTD subsets in [3.9 XML conformance](https://www.w3.org/TR/epub-33/#sec-xml-constraints) in EPUB 3.3.  But this change might invalidate some existing EPUB publications.

It is worth noting that some RSes such as Thorium do not expand references to internal parsed entities.  But this means that XML processing in Thorium does not conform to XML.
  

P.S.  I should have raised this issue long time ago.  I learned this issue when XML was being designed. My apology.

**Comment by iherman** [comment]
You are right that, at this stage (and, also, due to the charter restriction) we cannot forbid the usage of internal entities. Would a _SHOULD_ statement work? Ie, in the Core spec, we would say that XML files _SHOULD NOT_ use internal entities, and a similar statement would be put into the RS spec, whereby a RS _MAY_ decide not to expand internal entities (e.g., either globally, or when security problem is detected).

@bduga @davemanhall @wareid

**Comment by dauwhe** [comment]
https://en.wikipedia.org/wiki/Billion_laughs_attack

**Comment by mattgarrish** [comment]
> and a similar statement would be put into the RS spec, whereby a RS _MAY_ decide not to expand internal entities

Do we need to say anything normative? The discussion about external entities makes me wonder why we need to solve known XML attack vectors through normative requirements. Can't we just add an XML subsection to the security risks and note that RS devs need to consider that these threats may be present in any document since authoring restrictions aren't reliable?

**Comment by murata2makoto** [comment]
> SHOULD NOT use internal entities

I prefer 

> SHOULD NOT have internal DTD subsets

Ivan wrote:
>a RS MAY decide not to expand internal entities (e.g., either globally, or when security problem is detected).

This does not conform to the XML recommendation.

**Comment by iherman** [comment]
> > and a similar statement would be put into the RS spec, whereby a RS _MAY_ decide not to expand internal entities
> 
> Do we need to say anything normative? The discussion about external entities makes me wonder why we need to solve known XML attack vectors through normative requirements. Can't we just add an XML subsection to the security risks and note that RS devs need to consider that these threats may be present in any document since authoring restrictions aren't reliable?

That would also work for me.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-10-07-epub#section2) on 2022-10-07

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 2. XML security risk: expansion of internal parsed entities (issue epub-specs#2447)

_See github issue [epub-specs#2447](https://github.com/w3c/epub-specs/issues/2447)._




_See github issue [epub-specs#2433](https://github.com/w3c/epub-specs/issues/2433)._




**Murata Makoto:** old issue; more than 20 years ago.  
… related to external parsed entities issue 2433.  
… this issue is about INTERNAL parsed entities.  
… doesn't use external identifiers or URLs.  
… these are defined in internal DTD subsets.  

> *Dave Cramer:* See [description of the attack](https://en.wikipedia.org/wiki/Billion_laughs_attack).

**Murata Makoto:** if an internal reference references a different internal reference, things can get out of hand quickly.  
… some EPUB reading systems ignore rec of XML and ignore internal parsed entities. This is non-conformant but avoids security issue.  
… what should we do? Prohibit internal DTD subsets?.  
… which gets rid of internal parsed entities..  
… can exissting RSes be destryeed by malicious content?.  

_See github pull request [epub-specs#2451](https://github.com/w3c/epub-specs/pull/2451)._




**Ivan Herman:** thanks Makoto for raising the issue.  
… the problem is that removing the possibility to use internal entities is something we can't do because of existing epub docs that might use this.  
… we cannot invalidate existing content per our charter.  
… as part of a pull request that makoto and I did together is a separate section.  
… in the security section of RS spec.  

> *Ivan Herman:* See [proposed text in the PR's security section](https://raw.githack.com/w3c/epub-specs/makoto-xml-conformance-change/epub33/rs/index.html#security-privacy-recommendations).

**Ivan Herman:** which say that RS should be aware of this problem and should deal with it..  
… so we should draw attention to the issue.  

**Dave Cramer:** I don't think we can or should forbid internal entities.  
… the problem has been around 20 years and EPUB is still functional.  
… it's a security vulnerability, we may need to warn people in our security section.  
… ordering RSs to follow a specific algorithm might be overkill.  
… let's warn people.  

**Murata Makoto:** Basically, not our problem.  

**Brady Duga:** this is a known problem in XML. Are there known solutions?.  
… do they have mitigations? Like in libxml?.  

> *Dave Cramer:* "Defenses against this kind of attack include capping the memory allocated in an individual parser if loss of the document is acceptable, or treating entities symbolically and expanding them lazily only when (and to the extent) their content is to be used.".

**Ivan Herman:** makoto may know about libraries.  
… makoto made some sample epubs, and we tested them.  
… I tested on Thorium and Apple Books.  
… both reacted by rejecting the EPUB.  
… without identifying the problem.  
… we suspect they don't accept internal entities.  

**Murata Makoto:** I'm not aware of general solutions.  
… XML WG was aware of this issue, but had no good solutions.  
… thorium doesn't reject publication, it ignores the entity but not the entire publication.  
… this behavior is non-conformant.  

**Dave Cramer:** I don't think it's entirely fair to say that this implementation is non-conformant because it's not deploying my vulnerability.  
… not fair to RS.  

**Wendy Reid:** it's like the viewport discussion.  
… we want to avoid putting burdens on readers.  
… does the fail quietly solution work?.  
… is that a bad thing?.  
… I think because we are running out of time.  
… people should look at the PR.  
… there are other things in the PR.  
… then we move on.  

**Dave Cramer:** I think we add something to the security section.  
… it hasn't been a problem in the past, internal entities aren't usually a problem unless malicious.  
… what are the consequences of a malicious use.  
… the consequences seem small.  
… good enough to say "XML has a known vulnerability:.  

**Brady Duga:** I agree putting this in the security section, maybe mentioning other xml vulnerabilities.  
… any attack like this can jeopardize personal information.  
… although no one has bothered to do this.  

**Dave Cramer:** Some of this is also outside the scope of the WG, we can't ask for people to patch the OS they are running dev machines on.  

**Wendy Reid:** consensus: let's look people look at Ivan's PR.  
… comment on it.  
… ten minutes remaining.  
… two more topics.  

</details>
