### ISSUE TITLE
Add recommendation or requirement about the existence of xml:lang on alternate-script meta-element

### ISSUE THREAD

**Issue by Jesse-Bakker** [mattgarrish/epub-revision#2465]
An `alternate-script` meta element without an `xml:lang` attribute is not very useful and inheriting it from the `metadata` or `package` element should IMO be considered an anti-pattern (the refined metadata (`dc:title`, `dc:creator`, etc) overrides the base `xml:lang` only to be refined by the base `xml:lang` again).

A recommendation would look like:

When specifying an `alternate-script` property, creators SHOULD include an `xml:lang` attribute identifying the language and script of the associated property value.

**Comment by iherman** [comment]
I am not claiming to be an expert in the area @Jesse-Bakker, but I could see cases when the language tag is not really necessary. There are a number of languages (Japanese and Azeri come to my mind) that have different scripts that can be used for the same language.  I know [language tags](https://www.w3.org/International/articles/language-tags/) include script subtags, and I also know that they are widely used in some cases (e.g., zh-Hans or az-Latn) and it is indeed a good idea to use them, but I do not know whether, say, there is a usage for Japanese Hirigana vs. Kanji. 

That being said, using a _SHOULD_ does allow for _not_ using the feature for cases when it is not necessary.

Cc: @mattgarrish @r12a @xfq 

(For reference to readers who may not know what exactly is referred to in the issue, here is the [EPUB Spec reference](https://www.w3.org/TR/epub-33/#sec-alternate-script).)

**Comment by mattgarrish** [comment]
I'm kind of uneasy about saying there should or must be an `xml:lang` on the `meta` element just because you could reverse the example in the spec to:

```
<package .. xml:lang="en">
   ...
   <dc:creator id="aut" xml:lang="ja">村上 春樹</dc:creator>
   <meta property="alternate-script" refines="#aut">Haruki Murakami</meta>
```

And there's nothing technically wrong with this, even if it probably isn't common.

Is this perhaps more of an epubcheck issue? The definition says that:

> The alternate-script property provides an alternate expression of the associated property value in a language and script identified by the xml:lang attribute.

By this definition, I would expect both the original metadata expression and the alternate to have different languages associated with them regardless of where, or whether (in theory one could omit an `xml:lang`), the `xml:lang` attribute is specified -- there's an implicit must in the way it's worded. Epubcheck should be able to enforce that.

If we want to account for different language declaration locations, though, the definition might need updating more along the lines of:

> The `alternate-script` property provides an alternate expression of the associated property value in a different language and/or script. The language tags of the `alternate-script` property and its associated property -- as expressed by their respective in-scope `xml:lang` attributes -- MUST NOT be the same.

/cc to @murata2makoto, as well, as this property came out of the internationalization task force.

**Comment by iherman** [comment]
> > The `alternate-script` property provides an alternate expression of the associated property value in a different language or script. The language of the `alternate-script` property and its associated property -- as expressed by their respective in-scope `xml:lang` attributes -- MUST NOT be the same.
> 

@mattgarrish we should be careful: not _The language_ but _The language tag_. The language (Azeri) might be the same, but the alternate may be in a different script.

**Comment by mattgarrish** [comment]
> not _The language_ but _The language tag_

Yes, thanks, my bad.

**Comment by r12a** [comment]
Slightly off-topic, but not worth raising a new issue: There isn't normally a gap between names in 村上 春樹 as seen in example 83.
