### ISSUE TITLE
Sample codes use roles on html body

### ISSUE THREAD

**Issue by Ship10** [mattgarrish/epub-revision#2528]
Sample codes in EPUB Accessibility Techniques 1.1 [Section 4.3.2](https://www.w3.org/TR/epub-a11y-tech-11/#sem-002) use roles on html body. 
```
<html … >
   …
   <body
       role="doc-part">
      <h1>Part 1</h1>
   </body>
</html>
```
Should there be a section wrapper to apply roles? And I wonder if it is necessary to add another heading ahead of the section wrapper to get a conforming outline.

**Comment by mattgarrish** [comment]
It looks like the example dates to when we were still discussing `epub:type` for semantics.

It's not that it's not necessary to add a part wrapper as the lead-in text says, but that it's invalid because roles are not allowed on the `body` element (or only a couple are, and none from DPUB-ARIA).

I think we could end the section without showing the invalid example, or we could move the role to a wrapper section. I'd expect a publisher would opt to use aria-label rather than put in a visible heading, though.

**Comment by mattgarrish** [comment]
(Reminder to myself when I amend the document, but the section heading should say not to repeat roles. "Semantics" correlates to epub:type use.)
