### ISSUE TITLE
Allow xml:lang and dir on dc:source

### ISSUE THREAD

**Issue by mattgarrish** [mattgarrish/epub-revision#2635]
I know the ideal is that dc:source should specify an isbn or similar identifier, but it's not a requirement since there may not always be one (e.g., converting a word doc to an epub). Sometimes you have to write a description of the source.

I noticed just now that the [general DC optional element definition](https://www.w3.org/TR/epub-33/#sec-opf-dcmes-optional-def) doesn't allow these attributes on that element. Seems like an oversight when we created that definition since even epubcheck allows them.

I'm not sure if this rises above a level 2 change or not. We're clarifying where the attributes are allowed, but practically I don't think this requires anything new of reading systems. I'm going to mark it as class 2 for now but feel free to change.

**Comment by iherman** [comment]
> I know the ideal is that dc:source should specify an isbn or similar identifier, but it's not a requirement since there may not always be one (e.g., converting a word doc to an epub). Sometimes you have to write a description of the source.
> 

Just to underline what you say, the [DCMI definition](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/elements11/source/) says:

"Recommended best practice is to identify the related resource by means of a string conforming to a formal identification system."

And we use `dc:source` in EPUB without further restriction.

> Seems like an oversight when we created that definition since even epubcheck allows them.

+1

> 
> I'm not sure if this rises above a level 2 change or not. We're clarifying where the attributes are allowed, but practically I don't think this requires anything new of reading systems. I'm going to mark it as class 2 for now but feel free to change.

It may be new to the reading system, because it could affect the way the source value is presented to the end user. But this is not specified by EPUB. Consequently, I think Class 2 is fine.

**Comment by jenstroeger** [comment]
@mattgarrish @iherman would “localizing” using `xml:lang` also apply to [`dc:date`](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/) — though the docs state that the value should be in ISO 8601 format…

**Comment by mattgarrish** [comment]
> would “localizing” using `xml:lang` also apply to [`dc:date`](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/)

This is an open question in #2650
